const VALIDATION_ERROR = 'VALIDATION_ERROR';
const SERVER_ERROR = 'SERVER_ERROR';
const NOT_FOUND_ERROR = 'RIDES_NOT_FOUND_ERROR';
const SUCCESS = 'SUCCESS';

const SERVER_ERROR_MESSAGE = 'Unknown error';


module.exports = {
  VALIDATION_ERROR: VALIDATION_ERROR,
  SERVER_ERROR: SERVER_ERROR,
  NOT_FOUND_ERROR: NOT_FOUND_ERROR,
  SUCCESS: SUCCESS,
  SERVER_ERROR_MESSAGE: SERVER_ERROR_MESSAGE
};
